services:
  remover:
    image: busybox
    command: sh -c "echo \"endpoints:\" > /tmp/endpoints"
    volumes: 
    - ./endpoints.txt:/tmp/endpoints
  db:
    image: mariadb
    volumes: 
    - /mnt/d/IPEX/Vol:/var/lib/mysql
    environment: 
     MYSQL_ROOT_PASSWORD: mypass
  ngrok1:
    build: ./ngrok
    environment: 
      NGROK_APP: app1:3000
    volumes:
    - ./endpoints.txt:/tmp/endpoints
  ngrok2:
    build: ./ngrok
    environment: 
      NGROK_APP: app2:3000
    volumes:
    - ./endpoints.txt:/tmp/endpoints
  ansible:
    build: ./ansible
    volumes:
    - ./endpoints.txt:/tmp/endpoints
  app1:
    build: ./APP1/
  app2:
    build: ./APP2/
  