services:
  remover:
    image: busybox
    command: sh -c "echo \"endpoints:\" > /tmp/endpoints"
    volumes: 
    - ./endpoints.txt:/tmp/endpoints
  db:
    image: mariadb:10.5.3-focal
    volumes: 
    - ./DockerVol/dbVol:/var/lib/mysql
    - ./DockerVol/my1.cnf:/etc/my.cnf
    environment: 
      MYSQL_ROOT_PASSWORD: mypass
  db2:
   image: mariadb:10.5.3-focal
   volumes: 
    - ./DockerVol/dbVol2:/var/lib/mysql
    - ./DockerVol/my2.cnf:/etc/my.cnf
   environment: 
      MYSQL_ROOT_PASSWORD: mypass    
  dbkc:
    image: mariadb:10.5.3-focal 
    volumes: 
    - ./DockerVol/Keycloak:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    healthcheck:
     test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD  
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    ports: 
      - "8080:8080"
      - "9990:9990"
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mariadb
      DB_ADDR: dbkc
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password

    volumes: 
      - ./DockerVol/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
    depends_on:
      - dbkc
  ngrok1:
    build: ./ngrok
    environment: 
      NGROK_APP: app1:3000
    volumes:
    - ./endpoints.txt:/tmp/endpoints
  ngrok2:
    build: ./ngrok
    environment: 
      NGROK_APP: app2:3000
    volumes:
    - ./endpoints.txt:/tmp/endpoints
  ansible:
    build: ./ansible/
    volumes:
    - ./endpoints.txt:/tmp/endpoints
  app1:
    build: ./APP1/
  app2:
    build: ./APP2/